import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Layout from '../components/Layout';
import EmailForm from '../components/EmailForm';
import Hero from '../components/Hero';
import Projects from '../components/Projects';
import About from '../components/About';
import Contact from '../components/Contact';
import Skills from '../components/Skills';


export default function Home() {
    return (
        <Layout home>
            <Head>
                <title>Dave Aigbe | CS Student</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/logoicon.ico"/>
            </Head>
            <main className={styles.container}>
                <section className={styles.core}>
                    {/*HERO*/}
                    <Hero/>

                    <hr className={styles.divider} id={'projects'}/>
                    {/*PROJECT LIST*/}
                    <Projects/>

                    <hr className={styles.divider} id={'skills'}/>
                    {/*SKILL LISTING*/}
                    <Skills/>

                    <hr className={styles.divider} id={'about'}/>
                    {/*ABOUT ME*/}
                    <About/>

                    <hr className={styles.divider} id={'contact'}/>
                    {/*CONTACT BTNS & FORM*/}
                    <Contact/>
                    <EmailForm/>
                </section>
            </main>
        </Layout>
    );
}
