import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Layout from "../components/Layout";
import EmailForm from "../components/EmailForm";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import About from "../components/About";
import Contact from "../components/Contact";
import Skills from "../components/Skills";

export default function Home() {
    return (
        <Layout home className={styles.container}>
            <Head>
                <title>Dave Aigbe | CS Student</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/logoicon.ico"/>
            </Head>
            <main className={styles.main}>
                {/*HERO*/}
                <section>
                    <Hero/>
                </section>

                {/*PROJECT LIST*/}
                <section className={styles.core} id={'projects'}>
                    <Projects/>
                </section>

                <hr/>
                {/*SKILL LISTING*/}
                <section className={styles.core} id={'skills'}>
                    <Skills/>
                </section>

                <hr/>
                {/*ABOUT ME*/}
                <section className={styles.core} id={'about'}>
                   <About/>
                </section>

                <hr/>
                {/*CONTACT BTNS & FORM*/}
                <section className={styles.core} id={'contact'}>
                    <Contact/>
                    <section>
                        <EmailForm />
                    </section>
                </section>
            </main>
        </Layout>
    );
}
